### ISSUE TITLE
Remove ntripServer_StartAtSurveyIn setting

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#228]
![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/200b2d0b-a203-4460-b178-1b93d5056953)

    8) Select survey-in radio: Bluetooth

This menu controls ntripServer_StartAtSurveyIn and looks like a vestige menu/setting. It may have been used once on the old RTK Firmware, but ntripServer_StartAtSurveyIn is also no longer used in that firmware as well. I'm going to remove.

**Comment by doug-foster** [comment]
btw - #8 does not have a counterpart on the web config form.  no action needing, I was just mentioning since I'm comparing the serial menu to the web config menu.
<img width="658" alt="Screenshot 2024-04-05 at 6 47 37 PM" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/c6a05ec5-cca6-408a-a4dd-216f64d031ee">

**Comment by nseidle** [comment]
A good sanity check - thank you!
