### ISSUE TITLE
NTRIP Client setting modified upon entering WiFi config

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#263]
NTRIP Client is disabled no matter what, when entering WiFi config.

**Comment by nseidle** [comment]
Fixed in [this commit](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/commit/1dc5ff7aaab439482281fbf652da0063dbb94e1c).

**Comment by PaulZC** [comment]
This is definitely better than it was, but has - I think - created a new issue:

When I click Save Configuration, it gets stuck on Saving...

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/162a403d-07bd-4a98-b4a2-f3856822e57e)

I think because the websocket gets closed before the "receipt confirmation" is actually sent

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/18b5ecf3-3b5f-4e01-9cf0-6813e11d2f14)

I see "Sending receipt confirmation", but I never see it arrive in the console log. With [this line](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/4142eecb6b979a186211ff5940fee6cc4600a9c6/Firmware/RTK_Everywhere/AP-Config/src/main.js#L83) uncommented, I should see the "confirmDataReceipt,1," in the console log, but I don't...

**Comment by PaulZC** [comment]
But I do see "All Saved" on my iPhone through the captive portal.... Curious!

**Comment by PaulZC** [comment]
Update: Tuesday April 30th 9:40 Mountain Time
Code: release_candidate - with the #265 merged and form.h updated
Hardware: Torch

Default code settings - s,r,y - no WiFi credentials

WiFi config on Windows desktop, Chrome, _not_ captive portal

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/8b671827-df57-482b-b1c7-4a0ea82f3e4d)

Turn on Debug WiFi Config - s,n,4

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/2d6369fd-69fa-4e13-912d-4beaa083350f)

Provide sparkfun-iot credentials, enable PointPerfect - through the web config. Restart.

Torch connects to WiFi, receives PointPerfect corrections, gets RTK Float.

Return to WiFi config and save settings:

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/c88a8b71-41c9-45b6-9ccc-d6dab2f5d079)

We're all good...

I'm declaring my earlier issue to be caused by connecting to the wrong Torch - which was possibly running dubious firmware....

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
