### ISSUE TITLE
Torch: Add support for Galileo E6 

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#281]
Get [HAS](https://gssc.esa.int/navipedia/index.php/Galileo_High_Accuracy_Service_(HAS)) working. This requires the UM980 firmware to be updated. v11833 pushed to [repo](https://github.com/sparkfun/SparkFun_RTK_Torch/tree/main/UM980_Firmware). We will need a way to upload firmware to the UM980.

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/c0cfe5cd-cd67-4756-9e93-1d70a6c9f967)

Command 

    CONFIG PPP ENABLE E6-HAS

**Comment by nseidle** [comment]
E6 works well:

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/8d321758-8593-40c9-86b3-c7474b4a6c04)

**Comment by avinabmalla** [comment]
@nseidle you can also set the PPP convergence threshold. This would change the solution status to RTK Float (NMEA Fix type 5) when the solution accuracy is better than the specified threshold. This would be useful for example, when using SW Maps with the "Minimum Fix Quality" setting enabled to prevent recording of inaccurate points.

Also, please make sure the DATUM is set to WGS84 instead of PPPORIGINAL.

`CONFIG PPP DATUM WGS84`

**Comment by nseidle** [comment]
Thanks @avinabmalla! Will do. Also, I just updated the [Unicore library](https://github.com/sparkfun/SparkFun_Unicore_GNSS_Arduino_Library/releases) with some HASA/E6 examples. Let me know (over on that repo) if you see anything amiss.

**Comment by nseidle** [comment]
![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/7d654e80-8881-49dc-9dc4-1bdde04d9754)

**Comment by nseidle** [comment]
This is in [v1.1](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.1).
